version: '3.5'
services:
  flasksemaphore:
    image: pyflasksemaphore
    container_name: semaphore-pyflask-docker_flasksemaphore_1
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - vrt97/pyflasksemaphore
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
    environment:
      - PORT=5000