apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    run: app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: app
          image: gcr.io/search-engine-40179863-cd/app:latest
          ports:
            - containerPort: 8080